import os
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from flask import Flask, render_template, request
from google import genai
from google.genai import types

app = Flask(__name__)

# --- CONFIGURATION ---
PROJECT_ID = "macro-chef-app"
LOCATION = "us-central1"

# Email Configuration (We will set these in Cloud Run later)
SENDER_EMAIL = os.environ.get('SENDER_EMAIL')
SENDER_PASSWORD = os.environ.get('SENDER_PASSWORD')

try:
    client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)
    print(f"✅ Google Gen AI Client Connected")
except Exception as e:
    print(f"⚠️ Client Init Error: {e}")
    client = None

@app.route('/')
def index():
    return render_template('index.html', active_tab='chef')

@app.route('/generate-recipe', methods=['POST'])
def generate_recipe():
    if not client: return render_template('index.html', recipe="Error: Client not connected", active_tab='chef')
    
    ingredients = request.form.get('ingredients')
    prompt = f"""
    You are a helpful nutrition chef. User ingredients: {ingredients}.
    Create one creative recipe formatted as clean HTML (using Bootstrap classes).
    Structure: <h3>Name, <ul> Ingredients, <ol> Steps.
    """
    try:
        response = client.models.generate_content(model="gemini-2.0-flash-exp", contents=prompt)
        clean_html = response.text.replace("```html", "").replace("```", "")
        return render_template('index.html', recipe=clean_html, active_tab='chef')
    except Exception as e:
        return render_template('index.html', recipe=f"Error: {str(e)}", active_tab='chef')

# --- NEW EMAIL ROUTE ---
@app.route('/email-recipe', methods=['POST'])
def email_recipe():
    recipient = request.form.get('user_email')
    recipe_content = request.form.get('recipe_content') # We get the HTML from a hidden field
    
    if not SENDER_EMAIL or not SENDER_PASSWORD:
        return render_template('index.html', recipe=recipe_content, email_status="⚠️ Server Error: Email credentials not configured.", active_tab='chef')

    try:
        # Create the email
        msg = MIMEMultipart()
        msg['From'] = SENDER_EMAIL
        msg['To'] = recipient
        msg['Subject'] = "🍽️ Your Recipe from Chez Macro Chef"

        # Attach the HTML body
        # We wrap it in a div to make it look nice in the email client
        email_body = f"""
        <html>
            <body>
                <h2>Bon Appétit!</h2>
                <p>Here is the recipe you generated:</p>
                <hr>
                {recipe_content}
                <hr>
                <p><small>Generated by Macro Chef AI Agent</small></p>
            </body>
        </html>
        """
        msg.attach(MIMEText(email_body, 'html'))

        # Send via Gmail SMTP
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls() # Secure the connection
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()

        return render_template('index.html', recipe=recipe_content, email_status="✅ Recipe sent successfully!", active_tab='chef')

    except Exception as e:
        return render_template('index.html', recipe=recipe_content, email_status=f"❌ Failed to send: {str(e)}", active_tab='chef')


@app.route('/calculate-macros', methods=['POST'])
def calculate_macros():
    # ... (Keep your existing Math logic EXACTLY as it was in the previous step) ...
    # just abbreviated here for space, paste the logic from the previous turn
    if not client: return render_template('index.html', math_result="Error: Client not connected", active_tab='math')
    
    try:
        names = request.form.getlist('names[]')
        weights = request.form.getlist('weights[]')
        final_weight_str = request.form.get('final_weight')

        if not final_weight_str:
            return render_template('index.html', math_result="<div class='alert alert-danger'>Please enter a final weight.</div>", active_tab='math')
        
        final_weight = float(final_weight_str)
        ingredient_list_str = ", ".join([f"{n}: {w}g" for n, w in zip(names, weights) if n and w])

        prompt = f"""
        I have these raw ingredients: {ingredient_list_str}.
        Task: Estimate the total calories for each specific weight provided.
        Return ONLY a JSON object. No markdown.
        Format: {{ "items": [ {{ "name": "Chicken", "cals": 825 }} ], "total_cals": 1525 }}
        """

        response = client.models.generate_content(
            model="gemini-2.0-flash-exp", 
            contents=prompt,
            config=types.GenerateContentConfig(response_mime_type="application/json")
        )
        
        data = json.loads(response.text)
        total_raw_cals = data['total_cals']
        items = data['items']
        density = total_raw_cals / final_weight if final_weight > 0 else 0
        
        rows_html = ""
        for item in items: rows_html += f"<tr><td>{item['name']}</td><td>{item['cals']}</td></tr>"

        result_html = f"""
        <div class="alert alert-success">
            <h4 class="alert-heading">📊 Analysis Complete</h4>
            <table class="table table-sm table-borderless">
                <thead><tr><th>Ingredient</th><th>Est. Cals</th></tr></thead>
                <tbody>{rows_html}</tbody>
                <tfoot class="border-top"><tr><th>Total Raw</th><th>{total_raw_cals}</th></tr></tfoot>
            </table>
            <hr>
            <div class="text-center"><h2 style="color: #2A9D8F;">{density:.3f}</h2><p class="text-muted">Calories per Gram</p></div>
            <div class="bg-white p-3 rounded border">
                <strong>Serving Cheat Sheet:</strong>
                <ul class="mb-0">
                    <li>150g Serving = <strong>{round(density * 150)}</strong> cals</li>
                    <li>200g Serving = <strong>{round(density * 200)}</strong> cals</li>
                    <li>300g Serving = <strong>{round(density * 300)}</strong> cals</li>
                </ul>
            </div>
        </div>
        """
        return render_template('index.html', math_result=result_html, active_tab='math')

    except Exception as e:
        return render_template('index.html', math_result=f"Error: {str(e)}", active_tab='math')

if __name__ == "__main__":
    app.run(debug=True, host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))